columns:
  - id: int
  - Product ID: category
  - Type: category
  - Air temperature [K]: float
  - Process temperature [K]: float
  - Rotational speed [rpm]: int
  - Torque [Nm]: float
  - Tool wear [min]: int
  - Machine failure: int
  - TWF: int
  - HDF: int
  - PWF: int
  - OSF: int
  - RNF: int
target: Machine failure
drop_columns:
  - id
  - RNF
cat_columns:
  - Type
num_columns:
  - Product ID
  - Air temperature [K]
  - Process temperature [K]
  - Rotational speed [rpm]
  - Torque [Nm]
  - Tool wear [min]
  - TWF
  - HDF
  - PWF
  - OSF
  - Power
  - Temp Ratio
  - Torque X Tool wear
  - Tool Wear Rate